/* 
 * axxell-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package AxxellClient

// A store is equivalent to an user account
type Store struct {

	// Username/email used to login. Set this during registration.
	Email string `json:"email,omitempty"`

	// Also known as secret key. Read-only
	ApiKey string `json:"apiKey,omitempty"`

	// The password required to login. Set this during registration.
	Password string `json:"password,omitempty"`

	// Internal use
	Salt string `json:"salt,omitempty"`

	// Also known as access key. Read-only
	StoreId string `json:"storeId,omitempty"`
}
